service: line-bot-ocr
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action: "rekognition:DetectText"
      Resource: "*" 

functions:
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: post
    environment:
      LINE_ACCESS_TOKEN: "${ssm:/line/ocr/access_token~true}"
      LINE_CHANNEL_SECRET: "${ssm:/line/ocr/channel_secret~true}"

resources:
  Resources:
    ## dns setting
    Domain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: "${ssm:/acm/camelon.info~true}"
        DomainName: "ocr.camelon.info"

    Mapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName: { Ref: Domain }
        RestApiId:  { Ref: ApiGatewayRestApi }
        Stage: dev

    RecordSetOfAPI:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: "ocr.camelon.info"
        Type: A
        HostedZoneName: "camelon.info."
        AliasTarget:
          DNSName: { Fn::GetAtt: [Domain, DistributionDomainName] }
          HostedZoneId: Z2FDTNDATAQYW2
